DROP TABLE IF EXISTS Visit;
DROP TABLE IF EXISTS Place;
DROP TABLE IF EXISTS LocationOwner;
DROP TABLE IF EXISTS People;
DROP TABLE IF EXISTS Money;
DROP TABLE IF EXISTS GeneticMaterial;
DROP TABLE IF EXISTS Location;